### ISSUE TITLE
Gh-pages 404 

### ISSUE THREAD

**Issue by elbkr** [arifszn/gitprofile#123]
I set up config and vite.config, and when it deploys the site shows 404. I have already changed the branch to gh-pages.

The deploy shows `Configuration file: None`. It may be the problem?
https://github.com/elbkr/elbkr.github.io/runs/7640529874?check_suite_focus=true#step:4:11

**Comment by arifszn** [comment]
I can view your portfolio at https://elbkr.github.io. Can you confirm if you are still getting 404?

**Comment by elbkr** [comment]
I fixed it thanks ^^

**Comment by elbkr** [comment]
Hi, as you see it shows again 404. I looked into the website a few hours ago through the mobile and it was working

**Comment by arifszn** [comment]
I can still see it live.

**Comment by elbkr** [comment]
Maybe you have the site cached. Use ctrl +f5 and you'll see

**Comment by arifszn** [comment]
Yes, I did. I can still access it. However, closing this ticket as this issue is not related to this project. It's more a Github page issue/your device issue. You can contact Github Support.

**Comment by arifszn** [comment]
Btw, as I mentioned earlier, your site is live at https://elbkr.github.io. But you are having the issue at https://elbkr.is-a.dev. Seems like an issue of custom domain that `GitProfile` can't solve.

**Comment by arifszn** [comment]
After looking at your source code, I can see that you are trying to deploy it in a custom domain. Your site is accessible at https://elbkr.github.io as I mentioned earlier. But you are having 404 at https://elbkr.is-a.dev.

The reason behind the issue is that you have placed the CNAME file in the source code. But the site is deployed from [gh-pages](https://github.com/elbkr/elbkr.github.io/tree/gh-pages) branch. And there is no such CNAME file. That's why you can't access it from your custom domain.

**Comment by elbkr** [comment]
So how can I set it up to deploy the CNAME file to gh-pages branch??

**Comment by arifszn** [comment]
To apply custom domain:
- First, commit the CNAME file in `gh-pages` branch
- Then add `clean: true` in `.github/workflows/deploy.yml` file:
```yml
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
          clean: true
```

**Comment by elbkr** [comment]
it worked, thanks ^^

**Comment by arifszn** [comment]
Added in the discussion https://github.com/arifszn/gitprofile/discussions/126. Thanks for bringing out the issue.

**Comment by elbkr** [comment]
Hi, I fixed it thanks ^^
