### ISSUE TITLE
Medium Blog post thumbnail

### ISSUE THREAD

**Issue by uiopler** [arifszn/gitprofile#127]
![image](https://user-images.githubusercontent.com/75417088/183255728-bf1593fd-b039-4bed-a733-d143cac8f710.png)

As you see, the blog post is not showing the medium featured image. At the moment I am using the "Featured Image" system in Medium to show as a thumbnail on the portfolio, am I doing something wrong?

**Comment by arifszn** [comment]
I believe this issue is related to cache on Medium end. Let's wait for some time if the cache is refreshed.

**Comment by arifszn** [comment]
Is your medium username correct?
```js
blog: {
    source: 'medium', // medium | dev
    username: 'uiopler.dev',
    limit: '10',  // How many posts to display. Max is 10.
  },
```

Shouldn't it be `uiopler`?

**Comment by uiopler** [comment]
Yes it is, I have is as uiopler.dev on there

**Comment by uiopler** [comment]
speaking of blogs, dev doesnt even load

**Comment by arifszn** [comment]
https://medium.com/@uiopler.dev redirects to 404 page. Change it to `uiopler`.

Check the issues #69 for dev.

**Comment by uiopler** [comment]
Oh I must of changed it, Sorry for the trouble I have caused, thanks for helping!

**Comment by FahedHermoza** [comment]
Hi, in my case I have same error.

My username is @fahedhermoza and I also have subdomain fahedhermoza.medium.com. I don't understand which is my wrong.
![Captura de Pantalla 2024-01-07 a la(s) 17 33 40](https://github.com/arifszn/gitprofile/assets/8326973/70689cb7-320f-4e15-83fe-4600c91f8fc1)
![Captura de Pantalla 2024-01-07 a la(s) 17 33 49](https://github.com/arifszn/gitprofile/assets/8326973/d43a71c1-175d-4613-9276-8c3078ba457a)

**Comment by arifszn** [comment]
> Hi, in my case I have same error.
> 
> My username is https://medium.com/@fahedhermoza and I also have subdomain fahedhermoza.medium.com. I don't understand which is my wrong, please could you help me? ![Captura de Pantalla 2024-01-07 a la(s) 17 33 40](https://private-user-images.githubusercontent.com/8326973/294789487-70689cb7-320f-4e15-83fe-4600c91f8fc1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2OTIxNTEsIm5iZiI6MTcwNDY5MTg1MSwicGF0aCI6Ii84MzI2OTczLzI5NDc4OTQ4Ny03MDY4OWNiNy0zMjBmLTRlMTUtODNmZS00NjAwYzkxZjhmYzEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDhUMDUzMDUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTc5NmJlMjAxNzI2MjIxZDYzZGVmZjNhM2EzODdmODc3OTc0YTQ3MDU1OGE5OGMyZjg5NWRmNzUzZjZmMTFiYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.MGa7DdZ_bYf2MZmKuiD5upQEtTrluPPry_qfGvHZrvk) ![Captura de Pantalla 2024-01-07 a la(s) 17 33 49](https://private-user-images.githubusercontent.com/8326973/294789490-d43a71c1-175d-4613-9276-8c3078ba457a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2OTIxNTEsIm5iZiI6MTcwNDY5MTg1MSwicGF0aCI6Ii84MzI2OTczLzI5NDc4OTQ5MC1kNDNhNzFjMS0xNzVkLTQ2MTMtOTI3Ni04YzMwNzhiYTQ1N2EucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDhUMDUzMDUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2E5ZDcxNWVhMWUxNTQ0M2RlYmEzODdhNDVkYzAzZmUxZTIwZGRkMDg0YTRhNTNlZGIwY2U3NTU0MmYxNjc5NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.kjrxBV2G024qCNLopsUDXKkSqXqNyAANF-kKmA_XaiM)

A third-party tool is being used to extract the content of the medium. I tried with my username and it still returns an empty thumbnail, It's probably a temporary issue on the third-party platform. Let's wait a bit for them to fix them or I will move to another platform to extract the data.

**Comment by arifszn** [comment]
@FahedHermoza, the issue with the medium's thumbnail has been fixed. Running `npm i -D @arifszn/blog-js@latest` should fix it or let me know if you need any help.

**Comment by FahedHermoza** [comment]
Thanks for the response @arifszn,
Where can I run this command: npm i -D @arifszn/blog-js@latest ?

**Comment by arifszn** [comment]
In your local copy's terminal. If you do not have a local copy, it's best to clone it.

**Comment by FahedHermoza** [comment]
Thanks @arifszn:

![Captura de Pantalla 2024-03-02 a la(s) 11 01 09](https://github.com/arifszn/gitprofile/assets/8326973/716a819c-7c4f-49d3-a669-e7bbd6ccae24)

**Comment by golles** [comment]
I had the same issue, and just realized if I start my medium name with `@` it works fine, without it will not show a thumbnail, but does show articles.

**Comment by golles** [comment]
Ah, now the hyperlink for medium in the left panel has a double `@` in it... :-(

**Comment by arifszn** [comment]
I will take a look.

**Comment by arifszn** [comment]
> I had the same issue, and just realized if I start my medium name with `@` it works fine, without it will not show a thumbnail, but does show articles.

For me, it's showing the thumbnail without the @ sign. Also, the `social`'s `medium` property has no effect on displaying the articles as `blog` property controls it.

![image](https://github.com/arifszn/gitprofile/assets/45073703/8d7a5cd5-c797-49e4-9797-0106920d7ab7)
