### ISSUE TITLE
Make Repos Sortable

### ISSUE THREAD

**Issue by krillinkills** [arifszn/gitprofile#140]
Let the user decide the order of repos

**Comment by arifszn** [comment]
There are two options for ordering the repos. By star count or by recent update. A more explicit option will affect Github's [rate limits](https://docs.github.com/en/rest/overview/resources-in-the-rest-api).

https://github.com/arifszn/gitprofile/blob/ec3cdf4f683db516cfd33f9483ac4e001efd53c0/gitprofile.config.js#L6
