### ISSUE TITLE
Display one image of my github projects

### ISSUE THREAD

**Issue by zz9tf** [arifszn/gitprofile#151]
Hi Ariful,

Your gitprofile is pretty great, I'm just wondering if we could add one image above projects to make it looks more clear and funcy?

Just like what github does.

![image](https://user-images.githubusercontent.com/77183284/188032848-788be7cb-ea0e-48f6-b8fa-f2af70b5f9a3.png)

But I'm not sure how to do it yet, do you have any good idea?

**Comment by arifszn** [comment]
I will take a look if the image can be retrieved from the GitHub response.

**Comment by arifszn** [comment]
Unfortunately, GitHub API does not provide the social image URL. Please let me know if you find any other way.

**Comment by zz9tf** [comment]
Hi, I just found a method online, it's from GitHub GraphQL API v4.

![image](https://user-images.githubusercontent.com/77183284/188336036-45183d34-b1b2-4b3b-836a-4c3d252c8d6c.png)

Result of the link:
![image](https://user-images.githubusercontent.com/77183284/188336069-e059a06b-2722-4c7b-8463-d9b36af5a069.png)

With the above code, we can get the social image URL. Sorry about my limited experience with website development, I'm not sure if we can use it.
Origin source: https://stackoverflow.com/questions/56691229/how-can-i-get-my-social-preview-image-link-of-my-github-repo-using-git-api-or-an

**Comment by arifszn** [comment]
GitProfile is using the [GitHub REST API](https://docs.github.com/en/rest) instead of the GraphQL API. There are some major differences between those APIs. We have no plan for migrating to GraphQL currently. But any PR for the migration is welcome.
