### ISSUE TITLE
Website is fully white.

### ISSUE THREAD

**Issue by xdNuggets** [arifszn/gitprofile#169]
Just forked the portfolio, and im really impressed. I've always been awful at Web Dev so seeing such a good portfolio for completely free is just amazing.

I forked the repo, edited stuff to fit my needs, basically just removing most the socials and the sample experience and education text.
Yet when I upload it to github pages, the website is completely white. I'm not sure if this is an easy fix or a known issue, but a response back wouild be nice.

heres the website if you wanna see... https://xdNuggets.github.io/portfolio
and heres the repo: https://github.com/xdNuggets/portfolio

**Comment by arifszn** [comment]
Thank you a lot for the kind words. Means a lot.

Let me help you with the issue you are facing. I believe it's an easy fix.

Can you please check the source of your forked repo by visiting https://github.com/xdNuggets/portfolio/settings/pages? If it's not `Github Actions` change it to `Github Actions` please.

![image](https://user-images.githubusercontent.com/45073703/190852763-fd6ca4f3-4352-4d91-b644-fb83c4ce7797.png)

**Comment by xdNuggets** [comment]
It indeed wasn't Actions. I assumed the deployment part was unchanged so I went with my usual deployment process

**Comment by arifszn** [comment]
Let me know after changing it. Don't forget to trigger the workflow manually or by pushing any new commit.

**Comment by xdNuggets** [comment]
I changed it to github actions. Do I select Jekyll or just static html?

**Comment by xdNuggets** [comment]
Ah nvm! It works! Thanks for the quick responses, and thank you again for such a good portfolio for absolutely free

**Comment by arifszn** [comment]
Glad I could help. The Actions part is pretty new to GitHub so haven't able to document it fully. Thanks for bringing the issue up. Will add it to the readme soon.
