### ISSUE TITLE
Separate Repos and Projects sections

### ISSUE THREAD

**Issue by arifszn** [arifszn/gitprofile#182]
### Discussed in https://github.com/arifszn/gitprofile/discussions/96

<div type='discussions-op-text'>

<sup>Originally posted by **MehdiRtal** July 13, 2022</sup>
Would be better in my opinion if there's a separate section for showcasing your projects done separatly without having to publish them in GitHub as repos.</div>

**Comment by micheldore** [comment]
#185 Pull request added

**Comment by micheldore** [comment]
@arifszn Did you have time to take a look at the pull request?

**Comment by arifszn** [comment]
I will review it tomorrow. Was on holiday. Sorry for the delay.
