### ISSUE TITLE
Work experience details

### ISSUE THREAD

**Issue by Tkko** [arifszn/gitprofile#187]
Hey, I've just encountered this project and it is really good but to make it better, work experience details should be displayed under each item, something like this
![Screen Shot 2022-10-07 at 2 51 23 PM](https://user-images.githubusercontent.com/26390946/194536988-f9df5e4c-6f5b-4d20-b933-be1d997fdbb1.png)

**Comment by knittl** [comment]
Sounds useful. A simple list for each experience item should be fairly simple. In a second step, I could link company logos. Anybody working on this? Otherwise, I'd like to take a stab.

**Comment by arifszn** [comment]
> Sounds useful. A simple list for each experience item should be fairly simple. In a second step, I could link company logos. Anybody working on this? Otherwise, I'd like to take a stab.

We are holding this feature for now to prioritize other features. Too many features would eventually make this project look complex for new users. Thanks.
