### ISSUE TITLE
Add loading indicator for Download Resume button 

### ISSUE THREAD

**Issue by arifszn** [arifszn/gitprofile#188]
All the components have loading indicator except the `Download Resume` button. Add it for it too.
![Screenshot_2022-10-09-15-10-20-453_com android chrome](https://user-images.githubusercontent.com/45073703/194748258-ef3653c8-0d35-468b-96b0-f5dc0c49de65.jpg)

**Comment by whyang0808** [comment]
Hi, I would like to try on this.
