### ISSUE TITLE
Handle empty repositories of GitHub user

### ISSUE THREAD

**Issue by arifszn** [arifszn/gitprofile#218]
If the given GitHub user does not have any public repositories, it is showing an error. It needs to be handled.

![image](https://user-images.githubusercontent.com/45073703/197752504-8e54a75d-b592-4eca-93dc-d96ddfca4ddb.png)

Show a message for empty repositories or hide the `My Projects` section.

**Comment by Revortni** [comment]
I'd like to work on this

**Comment by arifszn** [comment]
Done. I think it's better to hide the section .

**Comment by Revortni** [comment]
Okay

**Comment by Revortni** [comment]
@arifszn  also is there a way to enable auto reloading when changes are saved? i would have thought it would work by default

**Comment by Revortni** [comment]
Do you have a user i can reference to test this?

**Comment by arifszn** [comment]
> Do you have a user i can reference to test this?

**`genita-tahiri`**
