### ISSUE TITLE
Upgrade `actions/cache` to v3 in test-deploy.yml

### ISSUE THREAD

**Issue by arifszn** [arifszn/gitprofile#221]
https://github.com/arifszn/gitprofile/blob/20cc39d7ce8eea34be0f383a028d12510b8657b2/.github/workflows/test-deploy.yml#L21

**Comment by arifszn** [comment]
@knittl would you like to take this one?

**Comment by knittl** [comment]
Sure, why not :)

**Comment by arifszn** [comment]
Close via #224.
