### ISSUE TITLE
Add support for Mastodon social

### ISSUE THREAD

**Issue by csarnataro** [arifszn/gitprofile#267]
Hi there, first of all, thank you for this project, I was looking for a way to publish my GitHub contributions and projects in an elegant way and `gitprofile` is exactly what I was looking for.

Since Mastodon is become more and more popular in the tech space, I think it would be great to have the possibility to add a link to a developer's Mastodon profile.

I just created a PR #266 .

Please let me know your thoughts.

**Comment by arifszn** [comment]
Thanks. Will review the PR tonight.

**Comment by arifszn** [comment]
https://github.com/arifszn/gitprofile/pull/266#issuecomment-1368194470

**Comment by arifszn** [comment]
Close via #266.
