### ISSUE TITLE
Hosting issues 

### ISSUE THREAD

**Issue by SrivamsiRajesh** [arifszn/gitprofile#273]
Hello there , 

I have tried hosting my portfolio with vercel but I got a blank screen and yea it did not work . I did try using github pages too my repos name is portfolio and in vite.config.js I did change the base to /portfolio/ . And over there too I got a blank page as a result . Are there any docs which can help me to host it in vercel ?

**Comment by arifszn** [comment]
You may need to remove `base` from vite.config.js for vercel. The base is only needed for GitHub pages.

https://vitejs.dev/guide/static-deploy.html#vercel

**Comment by arifszn** [comment]
And if you want to host using GitHub pages,
- when you set your base to '/portfolio/', the site will be available at SrivamsiRajesh.github.io/portfolio.
- when you set base to `/`, it will be available at SrivamsiRajesh.github.io.

**Comment by SrivamsiRajesh** [comment]
Thanks a lot mate . I did host my website thank you for this amazing package too . Have a great day
