### ISSUE TITLE
Blog Post

### ISSUE THREAD

**Issue by zakery1369** [arifszn/gitprofile#296]
in blog post section

// gitprofile.config.js
const config = {
  // ...
  blog: {
    source: 'dev',
    username: 'zakery1369',
    limit: 10,
  },
};

But it show 1 post from the dev!!!

source 'medium' is not a problem.

**Comment by arifszn** [comment]
Cache issue from dev.

https://github.com/arifszn/gitprofile/issues/69#issuecomment-1108842690
