### ISSUE TITLE
Adding Support  for Emojis

### ISSUE THREAD

**Issue by Nopock** [arifszn/gitprofile#324]
Is it possible to add support for emojis such as ⛏️ 

On the website it just appears as ```: pick : "

**Comment by arifszn** [comment]
Can you please add a screenshot?

**Comment by Nopock** [comment]
![image](https://user-images.githubusercontent.com/78834703/223309778-43e830e4-aeff-4ec3-91dc-3965c74c80a3.png)

The description just appears as 

: pick :  An AIO data storage library. : pick :

**Comment by Nopock** [comment]
Without the spaces between the : and pick because github doesnt allow it

**Comment by Nopock** [comment]
![image](https://user-images.githubusercontent.com/78834703/223310637-81910b07-6494-467f-9c3c-a840f0e7d2e1.png)
Specificallyon the website

**Comment by arifszn** [comment]
Ah got it. It has an easy solution though.

When I use `:rocket:`, GitProfile shows like this. 

<img width="284" alt="image" src="https://user-images.githubusercontent.com/45073703/223318636-83add5db-6bf3-4160-be26-44dede46fae7.png">

Then I copied the `🚀` emoji and pasted it replacing `:rocket:` in GitHub.

<img width="279" alt="image" src="https://user-images.githubusercontent.com/45073703/223318993-bc917742-9a72-49ab-a18a-d73c1070b219.png">

I am not sure if it's worth it to support the text emoji where using the actual emoji solves the issue.
