### ISSUE TITLE
page not loading

### ISSUE THREAD

**Issue by Bamboooz** [arifszn/gitprofile#350]
![image](https://user-images.githubusercontent.com/83116089/228976882-9bf89c13-b14b-4950-af7c-1573c1bfa6f8.png)

I forked the repository and changed the base value as asked, but when i open the page its whole white, what do i do?

**Comment by Bamboooz** [comment]
i got the actions enabled too

**Comment by arifszn** [comment]
I can see the last actions were run by the 'pages-build' instead of the custom workflow. Try pushing another commit to trigger the workflow.
![Screenshot_2023-03-31-04-26-26-639_com opera browser](https://user-images.githubusercontent.com/45073703/228977607-cd2d3bab-05b1-4885-b2ce-2609d87b2a45.jpg)

**Comment by Bamboooz** [comment]
so for example just a simple change in readme will be counted?

**Comment by arifszn** [comment]
Yes, also please check if Source is set to GitHub Actions in Settings ➜ Pages ➜ Build and deployment.

**Comment by Bamboooz** [comment]
did this commit, it is set but the issue was not resolved
![image](https://user-images.githubusercontent.com/83116089/228978427-2df30f9b-4664-4fad-809f-0b6bb7182eb4.png)

**Comment by Bamboooz** [comment]
changed to github actions, made another commit after it so it would work, but the issue is still not resolved

**Comment by Bamboooz** [comment]
![image](https://user-images.githubusercontent.com/83116089/228979370-83ed1373-345b-4bba-8d43-8f7e3cb5b364.png)
for me its still blank

**Comment by arifszn** [comment]
Try ctrl + f5 (Hard refresh)

**Comment by Bamboooz** [comment]
it worked, thanks! I will remember this shortcut.
