### ISSUE TITLE
Suggestion - remove capitalizing github projects.

### ISSUE THREAD

**Issue by Bamboooz** [arifszn/gitprofile#351]
![Screenshot_20230331-150045_Samsung Internet.jpg](https://user-images.githubusercontent.com/83116089/229127498-5b501218-aadb-48b8-b6a1-246ab3e42d1d.jpg)

I think that this is pretty annoying, that all github projects names are being capitalised, and I hope this will change in the future

**Comment by arifszn** [comment]
I will look into this.

**Comment by hkrvikrant** [comment]
I would like to solve this issue. Kindly assign this task to me
