### ISSUE TITLE
Bug: Hidden theme dropdown menu behind the profile card

### ISSUE THREAD

**Issue by aashay28** [arifszn/gitprofile#391]

**Comment by arifszn** [comment]
Please provide more context preferably a screenshot.

**Comment by aashay28** [comment]
![Screenshot 2023-06-07 at 4 19 04 PM](https://github.com/arifszn/gitprofile/assets/108337259/a1117881-fef4-481d-b032-b70defa11682)

**Comment by arifszn** [comment]
Which browser and Operating system are you using?

**Comment by aashay28** [comment]
Google chrome and macOS

**Comment by Ashakour1** [comment]
Chrome

**Comment by aashay28** [comment]
@arifszn  Generated the PR, please verify the same. Thanks.
