### ISSUE TITLE
Redirecting issue

### ISSUE THREAD

**Issue by AkhilProto** [arifszn/gitprofile#409]
So I have set up my website through the conf files and everything was working fine and then i suddenly noticed something... The url of my website(akhilproto.github.io) was redirecting to the homepage no matter what i keep after "akhilproto.github.io/". Let it be akhilproto.github.io/random or akhilproto.github.io/ecghbjhduich. It redirects me to the mainpage you see when you open akhilproto.github.io. Note - The url typed in the address bar remains the same. I mean it should show a Error 404 page right? I guess there is some problem with the code or a mistake from my end. Please let me know if there is any. Any help would be appreciated.

**Comment by AkhilProto** [comment]
I have just checked the other users' pages who are using this and noticed the same thing is happening with them also. Please look over it

**Comment by arifszn** [comment]
I was able to reproduce this issue and will look into soon.

Happening for recently created/updated project. For example, https://eduardokkkk.github.io/ doesn't have this issue. Might be a package update is causing this.

**Comment by AkhilProto** [comment]
Thank you for looking onto this

**Comment by AkhilProto** [comment]
Ok. Onto it

**Comment by arifszn** [comment]
Or, in `vite.config.js`, update the `VitePWA` as follows:
```js
    VitePWA({
      registerType: 'autoUpdate',
      workbox: {
        navigateFallback: undefined,
      },
      includeAssets: ['logo.png'],
      manifest: {
        name: 'Portfolio',
        short_name: 'Portfolio',
        description: 'Personal Portfolio',
        icons: [
          {
            src: 'logo.png',
            sizes: '64x64 32x32 24x24 16x16 192x192 512x512',
            type: 'image/png',
          },
        ],
      },
    }),
```

**Comment by AkhilProto** [comment]
Yes! It's working, now I'm getting the Error 404 page. Thank you for responding to my issue and solving it. Have a nice day!
