### ISSUE TITLE
Resume repo location instead of url

### ISSUE THREAD

**Issue by christos-vasileiou** [arifszn/gitprofile#511]
Isn't there any way to specify the resume location without providing a url? For example, isn't possible to upload the resume on the repo?

**Comment by tvanlaar** [comment]
Did you end up finding a fix for this?

**Comment by arifszn** [comment]
> Did you end up finding a fix for this?

Upload in the public folder and then use the URL like this: https://arifszn.github.io/gitprofile/logo.png
