### ISSUE TITLE
Add section for Publications

### ISSUE THREAD

**Issue by arifszn** [arifszn/gitprofile#519]
### Discussed in https://github.com/arifszn/gitprofile/discussions/515

<div type='discussions-op-text'>

<sup>Originally posted by **christos-vasileiou** February 26, 2024</sup>
Is there a possiblity to add a section for papers and journals publications? </div>

**Comment by arifszn** [comment]
Initial UI. Any suggestions?

![image](https://github.com/arifszn/gitprofile/assets/45073703/fe66ee97-9c01-4b5c-a5da-dba357d105a3)

**Comment by christos-vasileiou** [comment]
It looks perfect! One question. Is there a link for both code and paper? Because I cannot see it. When you clink on the tile where does the redirection drive you to?

**Comment by lindaboshans** [comment]
Thank you, this is fantastic and also what I was looking for! As suggested above, it would be useful if we could have two links, one to the publication and 1 to the code/github repository.

**Comment by arifszn** [comment]
I was thiking of a single link approach: clicking on the card will directly redirect users to the publication. This maintains consistency with previous cards, all of which follow this pattern. Additionally, considering that not all publications may include a code implementation link, having only one link avoids inconsistency. However, if a second link truly enhances the user experience, I'm open to exploring alternative solutions.

**Comment by arifszn** [comment]
Additionally, as a researcher, which social link would you like to include in this project? Would a ResearchGate link be suitable?
