### ISSUE TITLE
Vercel Deployment only shows a blank page

### ISSUE THREAD

**Issue by itzzjb** [arifszn/gitprofile#596]
@arifszn Hi, I tried to deploy this on Vercel. I left the default configuration. I was left with a blank page. Any idea on how to resolve this?

Thank you. 
Januda

**Comment by arifszn** [comment]
For deploying in Vercel, you might need to remove the base property from the config. Both key and value. It's needed for only deploying to GitHub page.

**Comment by itzzjb** [comment]
Hi 😄 thanks for the response.

So, you mean to change the base in `gitprofile.config.ts` to `/` right?

Now, it's like this. ( My repository name is also gitprofile)
```ts
  base: '/gitprofile/',
```

**Comment by arifszn** [comment]
> Hi 😄 thanks for the response.
> 
> So, you mean to change the base in `gitprofile.config.ts` to `/` right?
> 
> Now, it's like this. ( My repository name is also gitprofile)
> 
> ```ts
>   base: '/gitprofile/',
> ```

Yes, for Vercel, change it to `/`.

**Comment by itzzjb** [comment]
Is it ok if I changed my repository name to `itzzjb.github.io` so it would work on both Vercel and Github pages?

**Comment by arifszn** [comment]
> Is it ok if I changed my repository name to `itzzjb.github.io` so it would work on both Vercel and Github pages?

It won't work for Vercel.

**Comment by itzzjb** [comment]
Thanks, man, it worked. If it's okay can you tell me the reason why it's not working when we are using the base as `/gitprofile`? 

Sorry for the trouble. I am still learning.

**Comment by arifszn** [comment]
> Thanks, man, it worked. If it's okay can you tell me the reason why it's not working when we are using the base as `/gitprofile`?
> 
> Sorry for the trouble. I am still learning.

Vercel and Github page have different deployment strategies. For GitHub page, we need to point where the project is going to be hosted related to the root path. But on vercel, it's going to be hosted on the root path.

**Comment by itzzjb** [comment]
Ah ok, I got it now. Thanks for the help. Also thanks for this wonderful template. You're a lifesaver.  🫶
