### ISSUE TITLE
Unable to put forked repositories in GitHub project preview?

### ISSUE THREAD

**Issue by jonas4climate** [arifszn/gitprofile#615]
I noticed that when manually selecting projects that were forked, they don't show up in the GitHub project overview. Is this intended? I noticed also GitHub itself prevents pinning of forked repositories, perhaps that relates to this.

**Code:**
```
manual: {
  // Properties for manually specifying projects
  projects: [
    'jonas4climate/opinion-formation-complexity',
    'jonas4climate/metabolic-cellular-modelling', // Forked repo
    'jonas4climate/galaxy-zoo',
    'jonas4climate/modelling-natural-processes',
    'jonas4climate/numerical-algorithms-practice',
    'jonas4climate/learn_fourier',
  ],
},
```

**Resulting webpage:**
<img width="911" alt="Screenshot 2024-05-31 at 21 17 07" src="https://github.com/arifszn/gitprofile/assets/44198728/f1e8ebed-fe3b-467e-aea6-7d2f0710a118">

See my repository for reference on the config file: https://github.com/jonas4climate/jonas4climate.github.io

**Comment by arifszn** [comment]
Can you please share the forked repo's link?

**Comment by jonas4climate** [comment]
Sorry, my mistake... The original fork was private hence so too is my repo
