### ISSUE TITLE
medium articles 

### ISSUE THREAD

**Issue by propardhu** [arifszn/gitprofile#621]
medium articles are not getting displayed

**Comment by arifszn** [comment]
It's working for me. Please share the repository where you are having the issue.

**Comment by propardhu** [comment]
Here is my repo
https://github.com/propardhu/gitprofile_web

**Comment by arifszn** [comment]
![image](https://github.com/arifszn/gitprofile/assets/45073703/fde8ac83-62f3-4c5b-9ba2-b2d889863ff4)

Please check if your network provider is blocking medium.
