### ISSUE TITLE
dev blog posts not showing

### ISSUE THREAD

**Issue by penaxr** [arifszn/gitprofile#69]
It seems that on my end when I change the username to my dev username it will not show blog posts, But if I put the author's username it will show. 

I do have some blog posts on my dev account so I cannot figure out why this is happening.

thanks

**Comment by arifszn** [comment]
I got the username. The dev site uses caching mechanism so they have cached your recent article which was published today. I have faced this issue previously, it takes ususally one day to refresh the cached data. Let me know tomorrow.

**Comment by arifszn** [comment]
@penaxr any update on that?

**Comment by penaxr** [comment]
> @penaxr any update on that?
Sorry for the delay. It now works ! thanks for this awesome project
