### ISSUE TITLE
height issue 

### ISSUE THREAD

**Issue by gyanish0** [arifszn/gitprofile#75]
i am using footer and in this file already define css and i am not able to override this css please remove the classname .h-screen 
a i am attaching screenshot [also[](url)](![image](https://user-images.githubusercontent.com/91131495/169006537-0ff6ec8f-6f3e-4338-b6a3-baa5e2806a54.png))

**Comment by arifszn** [comment]
The class is required to place the footer at the bottom. It can't be removed or it will break the design for larger screens.

**Comment by gyanish0** [comment]
then how i can place a footer on the bottom

**Comment by gyanish0** [comment]
when i place then i get the data on 100vh height
