### ISSUE TITLE
https://poeticjustice1.github.io/

### ISSUE THREAD

**Issue by gavinmasese** [arifszn/gitprofile#79]
deployment is a success but the deployed site is not different

**Comment by arifszn** [comment]
I can see the config has not been changed. Change the username in line 5 of [this file](https://github.com/poeticjustice1/poeticjustice1.github.io/blob/main/gitprofile.config.js).

**Comment by arifszn** [comment]
@poeticjustice1, line 79 has invalid syntax. You have to provide a number on it. https://github.com/poeticjustice1/poeticjustice1.github.io/runs/6768764740?check_suite_focus=true

**Comment by arifszn** [comment]
@poeticjustice1 Now line 87.

**Comment by arifszn** [comment]
@poeticjustice1 I can see it is working now.
