### ISSUE TITLE
How to change body background color for a custom theme?

### ISSUE THREAD

**Issue by MehdiRtal** [arifszn/gitprofile#80]
Title.

**Comment by arifszn** [comment]
Change the value of `base-100`.

```js
// gitprofile.config.js

const config = {
  // ...,
  themeConfig: {
    customTheme: {
      // ...,
      'base-100': '#f2b6bd',
    },
  },
};
```

**Comment by MehdiRtal** [comment]
That's what I did earlier but it seems like only changes the boxes background color.

**Comment by MehdiRtal** [comment]
Can you specify what variable is for which?

**Comment by arifszn** [comment]
![image](https://user-images.githubusercontent.com/45073703/176641279-4ab31edf-575c-4123-9f64-aa11a5813eb4.png)

`base-100` is responsible for changing the bg of the body as well as of the cards. body uses `bg-base-200` and cards use `bg-base-100`.

**Comment by MehdiRtal** [comment]
Thanks but I used base-200 instead.
