### ISSUE TITLE
Install as Progressive Web App

### ISSUE THREAD

**Issue by arifszn** [arifszn/gitprofile#98]
Install GitProfile as a Progressive Web App. [PWA Vite Plugin](https://vite-plugin-pwa.netlify.app/) can be used.

**Comment by joanjeremiah** [comment]
I would like to solve this issue. Kindly assign this task to me

**Comment by arifszn** [comment]
Done.

**Comment by arifszn** [comment]
@joanjeremiah Any update on this?

**Comment by joanjeremiah** [comment]
I tried vite plugin and also react pwa template service registers. I couldn't make it work. I am still trying.

**Comment by micheldore** [comment]
I've taken a shot at this issue. Using the PWA vite plugin. #319
